# 项目主配置文件
# 包含项目运行的基本配置信息

# 应用配置
app:
  name: "GraphRAG"                    # 应用名称
  version: "1.0.0"                   # 应用版本
  debug: false                       # 是否开启调试模式
  host: "0.0.0.0"                   # 服务监听地址
  port: 5002                         # 服务监听端口
  secret_key: "your-secret-key-here" # Flask密钥，生产环境请修改
  
# 文件配置
file:
  upload_folder: "./upload"         # 文件上传目录
#  processed_folder: "./processed"    # 文件处理后存储目录
  temp_folder: "./temp"             # 临时文件目录
  max_file_size: 104857600          # 最大文件大小(100MB)
  allowed_extensions:               # 允许的文件扩展名
    - "pdf"
    - "docx"
    - "doc"
    - "xlsx"
    - "xls"
    - "pptx"
    - "ppt"
    - "txt"
    - "md"
    - "png"
    - "jpg"
    - "jpeg"
    - "gif"
    - "bmp"
  
  # 文件处理配置
  processing:
    chunk_size: 1000               # 文本分块大小
    chunk_overlap: 200             # 文本分块重叠
    enable_ocr: true               # 是否启用OCR
    ocr_language: "chi_sim+eng"    # OCR识别语言

# 日志配置
logging:
  level: "INFO"                     # 日志级别
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"  # 日志格式
  file_path: "./logs/app.log"       # 日志文件路径
  max_file_size: 10485760          # 日志文件最大大小(10MB)
  backup_count: 5                   # 日志文件备份数量
  enable_console: true              # 是否在控制台输出日志
  
# 安全配置
security:
  enable_cors: true                 # 是否启用CORS
  cors_origins: ["*"]              # CORS允许的源
  rate_limit: "100/hour"           # 请求频率限制
  enable_auth: false               # 是否启用认证
  
# 性能配置
performance:
  max_workers: 4                   # 最大工作线程数
  timeout: 300                     # 请求超时时间(秒)
  enable_profiling: false          # 是否启用性能分析