# 数据库配置文件
# 包含MySQL、Milvus、Neo4j的配置信息

# MySQL数据库配置
mysql:
  host: 192.168.16.26
  port: 3306
  username: root
  password: !200808Xx
  database: graph_rag
  charset: utf8mb4
  # 连接池配置
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30
  pool_recycle: 3600

# Milvus向量数据库配置
milvus:
  host: 192.168.16.26
  port: 19530
  database: graph_rag
  collection: graph_rag
  # 向量维度配置
  dimension: 768
  # 索引配置
  index_type: IVFFLAT
  nlist: 1024
  # 连接配置
  timeout: 30

# Neo4j图数据库配置
neo4j:
  host: 192.168.16.26
  port: 7687
  username: neo4j
  password: !200808Xx
  database: neo4j
  # 连接配置
  max_connection_lifetime: 3600
  max_connection_pool_size: 50
  connection_timeout: 30 