# 提示词配置文件
# 包含项目全局用到的所有提示词配置

# 文件处理相关提示词
file_processing:
  pdf_extract: |
    请从以下PDF内容中提取关键信息，包括：
    1. 文本内容
    2. 表格数据
    3. 图片描述
    4. 章节结构
    请以JSON格式返回结果。

# 智能检索相关提示词
search:
  query_analysis: |
    请分析以下用户查询，提取关键信息：
    1. 查询意图
    2. 关键词
    3. 实体信息
    4. 关系类型
    请以JSON格式返回分析结果。

  answer_generation: |
    基于以下检索到的文档内容，请生成准确、完整的答案：
    1. 确保答案与检索内容一致
    2. 保持逻辑清晰
    3. 引用相关文档片段
    4. 如果信息不足，请明确说明

# 图数据库相关提示词
graph:
  entity_extraction: |
    请从以下文本中提取实体信息：
    1. 人名
    2. 地名
    3. 组织机构
    4. 专业术语
    5. 时间信息
    请以JSON格式返回实体列表。

  relationship_extraction: |
    请从以下文本中提取实体间的关系：
    1. 实体对
    2. 关系类型
    3. 关系描述
    请以JSON格式返回关系列表。 