# 提示词配置文件
# 配置项目中使用的所有AI提示词模板

# 文档处理相关提示词
document_processing:
  # 文本内容提取提示词
  text_extraction: |
    请从以下文档内容中提取关键信息，保持原文的结构和重要细节：
    
    文档内容：
    {document_content}
    
    请按照以下格式输出：
    1. 主要内容摘要
    2. 关键信息点
    3. 重要数据和数字
    4. 专业术语和概念
  
  # 文档分块提示词
  text_chunking: |
    请将以下长文档按照语义完整性进行合理分块，每个分块应该：
    1. 保持语义完整
    2. 控制在{chunk_size}字符以内
    3. 避免截断重要信息
    
    文档内容：
    {document_content}

# 实体识别相关提示词
entity_recognition:
  # 命名实体识别提示词
  ner_extraction: |
    请从以下文本中识别并提取所有的命名实体，包括但不限于：
    - 人名
    - 地名
    - 组织机构名
    - 时间
    - 数量
    - 专业术语
    - 产品名称
    
    文本内容：
    {text_content}
    
    请以JSON格式返回，格式如下：
    {
      "persons": ["实体1", "实体2"],
      "locations": ["实体1", "实体2"],
      "organizations": ["实体1", "实体2"],
      "times": ["实体1", "实体2"],
      "quantities": ["实体1", "实体2"],
      "terms": ["实体1", "实体2"],
      "products": ["实体1", "实体2"]
    }

# 关系抽取相关提示词
relation_extraction:
  # 实体关系提取提示词
  entity_relations: |
    请分析以下文本中实体之间的关系，识别出主要的关系三元组：
    
    文本内容：
    {text_content}
    
    已识别的实体：
    {entities}
    
    请以JSON格式返回关系三元组，格式如下：
    {
      "relations": [
        {
          "head": "实体1",
          "relation": "关系类型",
          "tail": "实体2",
          "confidence": 0.95
        }
      ]
    }

# 智能问答相关提示词
question_answering:
  # 基于文档的问答提示词
  doc_qa: |
    基于以下文档内容回答用户问题，请确保答案准确、详细且有依据：
    
    相关文档内容：
    {relevant_docs}
    
    用户问题：
    {question}
    
    请提供详细的答案，并说明信息来源。如果文档中没有相关信息，请明确说明。
  
  # 基于知识图谱的问答提示词
  graph_qa: |
    基于以下知识图谱信息回答用户问题：
    
    相关实体和关系：
    {graph_info}
    
    用户问题：
    {question}
    
    请基于图谱信息提供准确的答案，并解释推理过程。

# 摘要生成相关提示词
summarization:
  # 文档摘要提示词
  document_summary: |
    请为以下文档生成一个简洁而全面的摘要，包含：
    1. 主要内容概述
    2. 关键观点
    3. 重要结论
    
    文档内容：
    {document_content}
    
    摘要长度控制在{summary_length}字以内。
  
  # 多文档摘要提示词
  multi_doc_summary: |
    请为以下多个相关文档生成综合摘要：
    
    {documents}
    
    请整合所有文档的信息，生成一个连贯的综合摘要。

# 文本生成相关提示词
text_generation:
  # 报告生成提示词
  report_generation: |
    基于以下信息生成一份专业的报告：
    
    主题：{topic}
    相关信息：{information}
    报告类型：{report_type}
    
    请按照标准报告格式生成，包含：
    1. 概述
    2. 详细分析
    3. 结论和建议